// Engine-aware test DB setup. Reads DATABASE_URL to decide between sqlite
// (file:./test.db in tmpdir) and postgresql (uses a fresh schema namespace per
// test file so parallel test files don't collide on the same Postgres database).
//
// Usage from a test file:
//
//   const testDb = await setupTestDb();
//   const prisma = createPrismaClient(testDb.dbUrl);
//   await testDb.applyMigration(prisma);
//
// The Prisma client and config are dependency-injected (createPrismaClient +
// buildApp(config, prisma) / attachWs(server, { config, prisma })), so tests
// just construct their own client against the isolated DB — no module-singleton
// reset, no `delete globalThis.prisma`, no dynamic imports.

import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
} from "node:fs";
import { randomBytes } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

export type Engine = "sqlite" | "postgresql";

// Postgres admin client used to CREATE / DROP SCHEMA in the test setup
// (separate from the per-schema PrismaClient that tests run against).
// Prisma 7 requires a driver adapter — the schema no longer carries the URL,
// and `new PrismaClient({ datasourceUrl })` no longer exists. The helper
// wraps a fresh pg.Pool per call so the admin connection is independent of
// the namespaced ones the test files own.
function pgAdminClient(url: string): PrismaClient {
  return new PrismaClient({
    adapter: new PrismaPg(new pg.Pool({ connectionString: url })),
  });
}

function detectEngine(url: string | undefined): Engine {
  if (!url) return "sqlite";
  if (url.startsWith("postgres://") || url.startsWith("postgresql://"))
    return "postgresql";
  return "sqlite";
}

function migrationsDir(engine: Engine): string {
  return engine === "postgresql"
    ? "prisma/postgres/migrations"
    : "prisma/migrations";
}

// Lists every migration.sql under the relevant migrations folder, in
// timestamp order. Applying them in sequence reproduces the full schema —
// the harness keeps working as the schema evolves across multiple migrations.
function findMigrationSqlFiles(engine: Engine): string[] {
  const dir = migrationsDir(engine);
  const entries = readdirSync(dir).filter((e) =>
    statSync(join(dir, e)).isDirectory(),
  );
  if (entries.length === 0) throw new Error(`no migrations found under ${dir}`);
  entries.sort();
  return entries.map((e) => join(dir, e, "migration.sql"));
}

// SQLite/Postgres error strings we silently tolerate. Migrations are
// generated by Prisma and assume an empty DB. In the test harness we still
// occasionally see the per-statement loop re-entered (e.g. a worker re-
// import) before the sentinel-table guard below has been written, so the
// regex layer remains as belt-and-suspenders for that window. Anything
// else still throws.
//
// Each provider phrases "already there" differently — match all of them:
//   - SQLite CREATE TABLE/INDEX collision:
//       "there is already another table or index with this name: …"
//   - Postgres / generic:
//       "relation \"…\" already exists", "column \"…\" already exists"
//   - SQLite ALTER TABLE ADD COLUMN of an existing column:
//       "duplicate column name: …"
//   - Postgres UNIQUE constraint on a re-applied seed row:
//       "duplicate key value violates unique constraint …"
const IDEMPOTENT_MIGRATION_ERRORS = [
  /already exists/i,
  /already another table or index/i,
  /duplicate column name/i,
  /duplicate key value/i,
];

// Exported for unit tests. The applyMigration loop is the only production
// caller; the test pins the pure-function behaviour so a regression to the
// regex set fails fast without spinning up a real database.
export function isIdempotentMigrationError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message : String(err);
  return IDEMPOTENT_MIGRATION_ERRORS.some((re) => re.test(msg));
}

// Sentinel table that records this harness has already applied the full set
// of migration files to this database. A second call to `applyMigration` on
// the same DB sees the sentinel and returns immediately — no statements
// replayed, no destructive RedefineTables steps run twice.
//
// We don't reuse Prisma's own `_prisma_migrations` table because we apply
// migrations via $executeRawUnsafe instead of `migrate deploy` — Prisma's
// migrations table is never populated in this code path, so we keep our own
// sentinel scoped to the harness and named distinctly.
const SENTINEL_TABLE = "_pane_test_migrations_applied";

async function migrationsAlreadyApplied(
  prisma: PrismaClient,
  engine: Engine,
): Promise<boolean> {
  // Cheap probe — read one row from the sentinel; treat "no such table" /
  // "does not exist" as "not yet applied", and any other error as fatal so we
  // don't silently no-op past a real DB problem.
  try {
    const rows =
      engine === "postgresql"
        ? await prisma.$queryRawUnsafe<{ ok: number }[]>(
            `SELECT 1 AS ok FROM "${SENTINEL_TABLE}" LIMIT 1`,
          )
        : await prisma.$queryRawUnsafe<{ ok: number }[]>(
            `SELECT 1 AS ok FROM "${SENTINEL_TABLE}" LIMIT 1`,
          );
    return rows.length > 0;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (/no such table/i.test(msg) || /does not exist/i.test(msg)) return false;
    throw err;
  }
}

async function markMigrationsApplied(prisma: PrismaClient): Promise<void> {
  // CREATE IF NOT EXISTS so a concurrent caller racing past the probe also
  // succeeds; both providers accept this form.
  await prisma.$executeRawUnsafe(
    `CREATE TABLE IF NOT EXISTS "${SENTINEL_TABLE}" ("applied_at" TEXT NOT NULL)`,
  );
  await prisma.$executeRawUnsafe(
    `INSERT INTO "${SENTINEL_TABLE}" ("applied_at") VALUES ('${new Date().toISOString()}')`,
  );
}

async function applyMigration(
  prisma: PrismaClient,
  engine: Engine,
): Promise<void> {
  // Guard: skip if already applied to this DB (re-entry safety).
  if (await migrationsAlreadyApplied(prisma, engine)) return;

  // Root cause of issue #118 (sqlite leg): Prisma's query engine maintains
  // a connection pool per PrismaClient. Each `$executeRawUnsafe` call may
  // grab a different connection. With per-connection SQLite snapshots
  // (WAL mode), the third migration's RedefineTables sequence
  //
  //   CREATE TABLE new_x; INSERT FROM x; DROP x; RENAME new_x → x; CREATE INDEX … ON x;
  //
  // can interleave across connections such that CREATE INDEX runs on a
  // connection that hasn't yet observed the RENAME, producing
  //   "no such table: main.artifact_versions"
  // on a freshly-created database.
  //
  // Fix: drive every statement through `$transaction(async (tx) => …)`.
  // Prisma's interactive transactions are pinned to a single connection,
  // so the RedefineTables sequence is observed atomically — every DDL
  // step sees the prior steps' effects.
  //
  // The per-statement regex-tolerance is preserved for the few residual
  // shapes (re-applied seed rows, ALTER ADD COLUMN race) that can still
  // throw inside the transaction; we re-throw anything else.

  const migrationFiles = findMigrationSqlFiles(engine);

  await prisma.$transaction(async (tx) => {
    for (const file of migrationFiles) {
      const raw = readFileSync(file, "utf8");
      const cleaned = raw
        .split("\n")
        .filter((l) => !l.trim().startsWith("--"))
        .join("\n");
      for (const stmt of cleaned
        .split(";")
        .map((s) => s.trim())
        .filter(Boolean)) {
        try {
          await tx.$executeRawUnsafe(stmt);
        } catch (err) {
          if (isIdempotentMigrationError(err)) continue;
          throw err;
        }
      }
    }
  });

  await markMigrationsApplied(prisma);
}

export interface TestDb {
  /** Connection URL to put into DATABASE_URL before importing src/db.ts. */
  dbUrl: string;
  /** Detected engine — for tests that need to branch on it. */
  engine: Engine;
  /** Apply the init migration. Call once per test file after dbUrl is set. */
  applyMigration: (prisma: PrismaClient) => Promise<void>;
  /** Drop all rows in dependency order — call from beforeEach. */
  truncateAll: (prisma: PrismaClient) => Promise<void>;
  /** Tear down per-file state (tmpdir for sqlite, schema for postgres). */
  cleanup: () => Promise<void>;
}

/**
 * Set up a per-file test database.
 * - sqlite: opens a fresh file in a tmpdir; deletes the tmpdir on cleanup.
 * - postgresql: uses the existing DATABASE_URL, but isolates this file's data
 *   inside a freshly-created schema (search_path) so parallel test files don't
 *   step on each other.
 */
export async function setupTestDb(): Promise<TestDb> {
  const engine = detectEngine(process.env.DATABASE_URL);

  if (engine === "sqlite") {
    const dir = mkdtempSync(join(tmpdir(), "pane-test-"));
    const dbUrl = `file:${join(dir, "test.db")}`;
    return {
      dbUrl,
      engine,
      applyMigration: (p) => applyMigration(p, "sqlite"),
      truncateAll: async (p) => {
        await p.feedback.deleteMany();
        await p.event.deleteMany();
        await p.participant.deleteMany();
        // Blobs FK agent with ON DELETE RESTRICT (an agent cannot be deleted
        // while it still owns attachments) — must go before the agent purge. Blobs
        // also FK surface + template (ON DELETE CASCADE), so per-table order
        // for those doesn't matter for the attachment rows themselves.
        // AttachmentTokens FK attachment with CASCADE; deleting attachment rows takes them
        // along, but doing it explicitly first keeps the row counts honest
        // when tests assert on token counts.
        await p.attachmentToken.deleteMany();
        await p.attachment.deleteMany();
        await p.surface.deleteMany();
        await p.templateVersion.deleteMany();
        await p.template.deleteMany();
        await p.agent.deleteMany();
      },
      cleanup: async () => {
        rmSync(dir, { recursive: true, force: true });
      },
    };
  }

  // Postgres: carve out a private schema per test file so files don't collide.
  // The CI workflow provides DATABASE_URL pointing at a real Postgres; we
  // append `?schema=<random>` so the migrations land in an isolated namespace.
  const base = process.env.DATABASE_URL!;
  const schemaName = `t_${randomBytes(8).toString("hex")}`;
  const u = new URL(base);
  u.searchParams.set("schema", schemaName);
  const dbUrl = u.toString();

  // We need a one-shot connection on the BASE url to CREATE SCHEMA, then the
  // returned dbUrl is what tests actually use.
  const admin = pgAdminClient(base);
  await admin.$executeRawUnsafe(`CREATE SCHEMA IF NOT EXISTS "${schemaName}"`);
  await admin.$disconnect();

  return {
    dbUrl,
    engine,
    applyMigration: (p) => applyMigration(p, "postgresql"),
    truncateAll: async (p) => {
      // TRUNCATE ... CASCADE is faster than per-row deleteMany on PG and
      // resets the SERIAL sequence on Event.id, which keeps per-test
      // assertions about event ids stable.
      await p.$executeRawUnsafe(
        `TRUNCATE TABLE "attachment_tokens", "attachments", "feedback", "events", "participants", "surfaces", "template_versions", "templates", "agents" RESTART IDENTITY CASCADE`,
      );
    },
    cleanup: async () => {
      const cleanupAdmin = pgAdminClient(base);
      await cleanupAdmin.$executeRawUnsafe(
        `DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`,
      );
      await cleanupAdmin.$disconnect();
    },
  };
}
