// Engine-aware test DB setup. Reads DATABASE_URL to decide between sqlite
// (file:./test.db in tmpdir) and postgresql (uses a fresh schema namespace per
// test file so parallel test files don't collide on the same Postgres database).
//
// Usage from a test file:
//
//   const testDb = await setupTestDb();
//   const prisma = createPrismaClient(testDb.dbUrl);
//   await testDb.applyMigration(prisma);
//
// The Prisma client and config are dependency-injected (createPrismaClient +
// buildApp(config, prisma) / attachWs(server, { config, prisma })), so tests
// just construct their own client against the isolated DB — no module-singleton
// reset, no `delete globalThis.prisma`, no dynamic imports.

import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
} from "node:fs";
import { randomBytes } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";

export type Engine = "sqlite" | "postgresql";

function detectEngine(url: string | undefined): Engine {
  if (!url) return "sqlite";
  if (url.startsWith("postgres://") || url.startsWith("postgresql://"))
    return "postgresql";
  return "sqlite";
}

function migrationsDir(engine: Engine): string {
  return engine === "postgresql"
    ? "prisma/postgres/migrations"
    : "prisma/migrations";
}

// Lists every migration.sql under the relevant migrations folder, in
// timestamp order. Applying them in sequence reproduces the full schema —
// the harness keeps working as the schema evolves across multiple migrations.
function findMigrationSqlFiles(engine: Engine): string[] {
  const dir = migrationsDir(engine);
  const entries = readdirSync(dir).filter((e) =>
    statSync(join(dir, e)).isDirectory(),
  );
  if (entries.length === 0) throw new Error(`no migrations found under ${dir}`);
  entries.sort();
  return entries.map((e) => join(dir, e, "migration.sql"));
}

// SQLite/Postgres error strings we silently tolerate. Migrations are
// generated by Prisma and assume an empty DB, but the test harness applies
// them against per-file databases that may be re-applied (e.g. worker re-
// import) or hit by concurrent test files in pathological pool topologies.
// The migration is logically idempotent — every CREATE TABLE / CREATE INDEX
// is rewritten below to `IF NOT EXISTS`, every ALTER TABLE ADD COLUMN
// effectively no-ops if the column already exists — so swallowing these
// specific errors keeps the test suite stable without hiding real schema
// bugs; anything else still throws.
//
// Each provider phrases "already there" differently — match all of them:
//   - SQLite CREATE TABLE/INDEX collision (pre-IF NOT EXISTS rewrite):
//       "there is already another table or index with this name: …"
//   - Postgres / generic:
//       "relation \"…\" already exists", "column \"…\" already exists"
//   - SQLite ALTER TABLE ADD COLUMN of an existing column:
//       "duplicate column name: …"
//   - Postgres UNIQUE constraint on a re-applied seed row:
//       "duplicate key value violates unique constraint …"
const IDEMPOTENT_MIGRATION_ERRORS = [
  /already exists/i,
  /already another table or index/i,
  /duplicate column name/i,
  /duplicate key value/i,
];

// Exported for unit tests. The applyMigration loop is the only production
// caller; tests pin the pure-function behaviour so regressions to either
// the regex set or the SQL rewriter (below) fail fast without spinning up a
// real database.
export function isIdempotentMigrationError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message : String(err);
  return IDEMPOTENT_MIGRATION_ERRORS.some((re) => re.test(msg));
}

// Rewrite `CREATE TABLE "x" (` → `CREATE TABLE IF NOT EXISTS "x" (` and
// `CREATE [UNIQUE] INDEX "x" ON …` → `CREATE [UNIQUE] INDEX IF NOT EXISTS "x"
// ON …`, only when the original SQL does NOT already contain `IF NOT EXISTS`.
// Both SQLite and Postgres accept `IF NOT EXISTS` on these statements, so the
// transform is portable. The earlier tolerance-on-error path stays as belt-
// and-suspenders for cases this transform doesn't reach (e.g. ALTER TABLE
// ADD COLUMN, which has no portable `IF NOT EXISTS` on SQLite).
export function makeStatementIdempotent(stmt: string): string {
  // Already idempotent — leave it alone.
  if (/\bIF\s+NOT\s+EXISTS\b/i.test(stmt)) return stmt;
  // CREATE [UNIQUE] INDEX "name" → CREATE [UNIQUE] INDEX IF NOT EXISTS "name"
  let out = stmt.replace(
    /^(\s*CREATE\s+(?:UNIQUE\s+)?INDEX)\s+(?!IF\s+NOT\s+EXISTS\b)/i,
    "$1 IF NOT EXISTS ",
  );
  // CREATE TABLE "name" → CREATE TABLE IF NOT EXISTS "name"
  // (TEMP / TEMPORARY isn't used in our migrations, so keep this simple.)
  out = out.replace(
    /^(\s*CREATE\s+TABLE)\s+(?!IF\s+NOT\s+EXISTS\b)/i,
    "$1 IF NOT EXISTS ",
  );
  return out;
}

async function applyMigration(
  prisma: PrismaClient,
  engine: Engine,
): Promise<void> {
  for (const file of findMigrationSqlFiles(engine)) {
    const raw = readFileSync(file, "utf8");
    const cleaned = raw
      .split("\n")
      .filter((l) => !l.trim().startsWith("--"))
      .join("\n");
    for (const rawStmt of cleaned
      .split(";")
      .map((s) => s.trim())
      .filter(Boolean)) {
      const stmt = makeStatementIdempotent(rawStmt);
      try {
        await prisma.$executeRawUnsafe(stmt);
      } catch (err) {
        if (isIdempotentMigrationError(err)) continue;
        throw err;
      }
    }
  }
}

export interface TestDb {
  /** Connection URL to put into DATABASE_URL before importing src/db.ts. */
  dbUrl: string;
  /** Detected engine — for tests that need to branch on it. */
  engine: Engine;
  /** Apply the init migration. Call once per test file after dbUrl is set. */
  applyMigration: (prisma: PrismaClient) => Promise<void>;
  /** Drop all rows in dependency order — call from beforeEach. */
  truncateAll: (prisma: PrismaClient) => Promise<void>;
  /** Tear down per-file state (tmpdir for sqlite, schema for postgres). */
  cleanup: () => Promise<void>;
}

/**
 * Set up a per-file test database.
 * - sqlite: opens a fresh file in a tmpdir; deletes the tmpdir on cleanup.
 * - postgresql: uses the existing DATABASE_URL, but isolates this file's data
 *   inside a freshly-created schema (search_path) so parallel test files don't
 *   step on each other.
 */
export async function setupTestDb(): Promise<TestDb> {
  const engine = detectEngine(process.env.DATABASE_URL);

  if (engine === "sqlite") {
    const dir = mkdtempSync(join(tmpdir(), "pane-test-"));
    const dbUrl = `file:${join(dir, "test.db")}`;
    return {
      dbUrl,
      engine,
      applyMigration: (p) => applyMigration(p, "sqlite"),
      truncateAll: async (p) => {
        await p.event.deleteMany();
        await p.participant.deleteMany();
        await p.session.deleteMany();
        await p.artifactVersion.deleteMany();
        await p.artifact.deleteMany();
        await p.agent.deleteMany();
      },
      cleanup: async () => {
        rmSync(dir, { recursive: true, force: true });
      },
    };
  }

  // Postgres: carve out a private schema per test file so files don't collide.
  // The CI workflow provides DATABASE_URL pointing at a real Postgres; we
  // append `?schema=<random>` so the migrations land in an isolated namespace.
  const base = process.env.DATABASE_URL!;
  const schemaName = `t_${randomBytes(8).toString("hex")}`;
  const u = new URL(base);
  u.searchParams.set("schema", schemaName);
  const dbUrl = u.toString();

  // We need a one-shot connection on the BASE url to CREATE SCHEMA, then the
  // returned dbUrl is what tests actually use.
  const admin = new PrismaClient({ datasourceUrl: base });
  await admin.$executeRawUnsafe(`CREATE SCHEMA IF NOT EXISTS "${schemaName}"`);
  await admin.$disconnect();

  return {
    dbUrl,
    engine,
    applyMigration: (p) => applyMigration(p, "postgresql"),
    truncateAll: async (p) => {
      // TRUNCATE ... CASCADE is faster than per-row deleteMany on PG and
      // resets the SERIAL sequence on Event.id, which keeps per-test
      // assertions about event ids stable.
      await p.$executeRawUnsafe(
        `TRUNCATE TABLE "events", "participants", "sessions", "artifact_versions", "artifacts", "agents" RESTART IDENTITY CASCADE`,
      );
    },
    cleanup: async () => {
      const cleanupAdmin = new PrismaClient({ datasourceUrl: base });
      await cleanupAdmin.$executeRawUnsafe(
        `DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`,
      );
      await cleanupAdmin.$disconnect();
    },
  };
}
