// Unit tests for the polyglot defense + EXIF strip via sharp.
//
// Tests use real image bytes generated by sharp itself — no fixture files
// to maintain. Each test:
//   1. Builds a valid image (with optional polyglot tail / metadata).
//   2. Runs normaliseImage().
//   3. Asserts the polyglot payload is GONE from the normalised output,
//      the image dimensions are preserved, and sha256 reflects the new
//      (clean) bytes.

import { describe, it, expect } from "vitest";
import sharp from "sharp";
import {
  isNormalisable,
  normaliseImage,
  ImageNormalisationError,
} from "./normalize.js";

/** Build a small valid JPEG via sharp itself. */
async function jpeg(width = 8, height = 8): Promise<Buffer> {
  return sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 200, g: 100, b: 50 },
    },
  })
    .jpeg()
    .toBuffer();
}

async function png(width = 8, height = 8): Promise<Buffer> {
  return sharp({
    create: {
      width,
      height,
      channels: 4,
      background: { r: 50, g: 200, b: 100, alpha: 1 },
    },
  })
    .png()
    .toBuffer();
}

async function gif(width = 8, height = 8): Promise<Buffer> {
  return sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 0, g: 0, b: 255 },
    },
  })
    .gif()
    .toBuffer();
}

async function webp(width = 8, height = 8): Promise<Buffer> {
  return sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 255, g: 0, b: 200 },
    },
  })
    .webp()
    .toBuffer();
}

/**
 * Build a JPEG with EXIF (incl. a GPS tag) so we can verify the strip
 * actually removes it.
 */
async function jpegWithExif(): Promise<Buffer> {
  // sharp's withExif() accepts a plain object that gets serialised into
  // the EXIF segment of the output JPEG.
  return sharp({
    create: {
      width: 16,
      height: 16,
      channels: 3,
      background: { r: 100, g: 100, b: 100 },
    },
  })
    .withExif({
      IFD0: {
        Software: "pane test",
        Artist: "should-be-stripped",
      },
      GPS: {
        GPSLatitudeRef: "N",
        // sharp's EXIF writer expects rational strings — using a simple form
        // it accepts.
        GPSLatitude: "37/1,46/1,30/1",
      },
    })
    .jpeg()
    .toBuffer();
}

describe("normaliseImage — pass-through MIMEs", () => {
  it("does not call sharp for application/pdf (returns input unchanged)", async () => {
    const fake = Buffer.from("%PDF-1.4\n…");
    const result = await normaliseImage({
      bytes: fake,
      mime: "application/pdf",
    });
    expect(result.normalised).toBe(false);
    expect(result.bytes.equals(fake)).toBe(true);
    expect(result.sha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it("does not call sharp for image/svg+xml (caller must sanitise XML separately)", async () => {
    const fake = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>');
    const result = await normaliseImage({
      bytes: fake,
      mime: "image/svg+xml",
    });
    expect(result.normalised).toBe(false);
  });
});

describe("normaliseImage — polyglot drops appended payloads", () => {
  it("strips HTML appended after JPEG EOI", async () => {
    const realJpeg = await jpeg();
    // Confirm the polyglot tail makes it into the input bytes.
    const polyglot = Buffer.concat([
      realJpeg,
      Buffer.from(
        "<html><body><script>alert('xss')</script></body></html>",
        "utf8",
      ),
    ]);
    expect(polyglot.toString("latin1")).toContain("alert");

    const result = await normaliseImage({
      bytes: polyglot,
      mime: "image/jpeg",
    });
    expect(result.normalised).toBe(true);

    // The output is a clean JPEG. No script tags, no html tail.
    const asLatin = result.bytes.toString("latin1");
    expect(asLatin).not.toContain("<script>");
    expect(asLatin).not.toContain("</html>");
    expect(asLatin).not.toContain("alert");

    // Sniff: re-decode succeeds and reports JPEG dimensions.
    expect(result.width).toBeGreaterThan(0);
    expect(result.height).toBeGreaterThan(0);
  });

  it("strips trailing bytes after a PNG IEND chunk", async () => {
    const realPng = await png();
    const polyglot = Buffer.concat([
      realPng,
      Buffer.from("MZ\x90\x00MalwareEXEHeader", "binary"),
    ]);
    const result = await normaliseImage({
      bytes: polyglot,
      mime: "image/png",
    });
    expect(result.normalised).toBe(true);
    expect(result.bytes.toString("latin1")).not.toContain("MalwareEXEHeader");
  });

  it("strips trailing bytes after a GIF terminator", async () => {
    const realGif = await gif();
    const polyglot = Buffer.concat([
      realGif,
      Buffer.from("Rar!\x1a\x07\x00RARArchiveContent", "binary"),
    ]);
    const result = await normaliseImage({
      bytes: polyglot,
      mime: "image/gif",
    });
    expect(result.normalised).toBe(true);
    expect(result.bytes.toString("latin1")).not.toContain("RARArchiveContent");
  });

  it("strips trailing bytes after a WebP RIFF chunk", async () => {
    const realWebp = await webp();
    const polyglot = Buffer.concat([
      realWebp,
      Buffer.from("PK\x03\x04SuspiciousZipMarker", "binary"),
    ]);
    const result = await normaliseImage({
      bytes: polyglot,
      mime: "image/webp",
    });
    expect(result.normalised).toBe(true);
    expect(result.bytes.toString("latin1")).not.toContain(
      "SuspiciousZipMarker",
    );
  });

  it("rejects bytes that don't decode as the declared image format", async () => {
    const notAnImage = Buffer.from(
      "<!doctype html><html><body>just html</body></html>",
      "utf8",
    );
    await expect(
      normaliseImage({
        bytes: notAnImage,
        mime: "image/jpeg",
      }),
    ).rejects.toBeInstanceOf(ImageNormalisationError);
  });
});

describe("normaliseImage — EXIF + thumbnail strip", () => {
  it("strips EXIF metadata by default", async () => {
    const withExif = await jpegWithExif();
    // Sanity: the input does carry EXIF (sharp's metadata reader sees it).
    const inMeta = await sharp(withExif).metadata();
    expect(inMeta.exif).toBeDefined();

    const result = await normaliseImage({
      bytes: withExif,
      mime: "image/jpeg",
    });
    expect(result.normalised).toBe(true);

    // After the strip, the output has no EXIF segment.
    const outMeta = await sharp(result.bytes).metadata();
    expect(outMeta.exif).toBeUndefined();
  });

  it("preserves visible image dimensions across the strip", async () => {
    const withExif = await jpegWithExif();
    const result = await normaliseImage({
      bytes: withExif,
      mime: "image/jpeg",
    });
    expect(result.width).toBe(16);
    expect(result.height).toBe(16);
  });

  it("changes the bytes (and sha256) because metadata is removed", async () => {
    const withExif = await jpegWithExif();
    const result = await normaliseImage({
      bytes: withExif,
      mime: "image/jpeg",
    });
    expect(result.bytes.equals(withExif)).toBe(false);
    expect(result.sha256).not.toBe(
      (await import("node:crypto"))
        .createHash("sha256")
        .update(withExif)
        .digest("hex"),
    );
  });
});

describe("normaliseImage — idempotency + dimensions", () => {
  it("re-normalising a normalised image is byte-stable", async () => {
    const j = await jpeg(32, 32);
    const once = await normaliseImage({ bytes: j, mime: "image/jpeg" });
    const twice = await normaliseImage({
      bytes: once.bytes,
      mime: "image/jpeg",
    });
    expect(twice.bytes.equals(once.bytes)).toBe(true);
    expect(twice.sha256).toBe(once.sha256);
  });

  it("reports the right dimensions on a wide image", async () => {
    const j = await jpeg(64, 16);
    const result = await normaliseImage({ bytes: j, mime: "image/jpeg" });
    expect(result.width).toBe(64);
    expect(result.height).toBe(16);
  });
});

describe("isNormalisable", () => {
  it("returns true for the four supported raster formats", () => {
    expect(isNormalisable("image/jpeg")).toBe(true);
    expect(isNormalisable("image/png")).toBe(true);
    expect(isNormalisable("image/gif")).toBe(true);
    expect(isNormalisable("image/webp")).toBe(true);
  });

  it("returns false for SVG (caller responsibility) + PDF + others", () => {
    expect(isNormalisable("image/svg+xml")).toBe(false);
    expect(isNormalisable("application/pdf")).toBe(false);
    expect(isNormalisable("text/plain")).toBe(false);
    expect(isNormalisable("application/octet-stream")).toBe(false);
  });
});
