-- Enforce that (sessionId, identityId) is unique across the participants
-- table — including revoked rows. The mint route derives identityId
-- monotonically (ever-minted human count) so under serial mints the pair
-- is always unique, but two concurrent POSTs to
-- `/v1/sessions/:id/participants` can both read the same count and both
-- attempt `h_${N}`. The constraint serialises that at the DB layer
-- (P2002 on the loser); the route catches the error and retries against
-- the new count.
--
-- Pre-migration safety: the existing data should be clean — the prior
-- bug (#201 / fixed in #206) produced collisions one-at-a-time via the
-- single-row create path, and any in-flight collision would have failed
-- on a subsequent row insert anyway. The migration adds the index in a
-- single statement; if existing data happens to violate the constraint
-- on someone's deployment, the migration fails loudly with a clear
-- "duplicate values" error and the operator de-duplicates before
-- re-running. Documented in #215.
CREATE UNIQUE INDEX "participants_session_id_identity_id_key" ON "participants"("session_id", "identity_id");
